name: AquaticEmotes
version: '${project.version}'
main: xyz.larkyy.aquaticemotes.aquaticemotes.AquaticEmotes
api-version: '1.20'
depend:
  - ModelEngine
commands:
  aquaticemotes:
    aliases:
      - aemotes
      - aquaticemote
      - aemote
      - emotes
      - emote
